# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
