# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_auto_20190724_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='adventure_category',
        ),
        migrations.AddField(
            model_name='adventure',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
