# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_auto_20190724_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='rating',
        ),
        migrations.AddField(
            model_name='message',
            name='rating',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, related_name='adventure_ratings', to='app_1.Adventure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
