# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_auto_20190724_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='likes',
        ),
    ]
